const ENUM_LABELS: Record<string, string> = {
  CUSTOMER: 'Cliente',
  STAFF: 'Personal',
  AUTHORITY: 'Autoridad',
  REGULAR: 'Regular',
  VIP: 'VIP',
  PREMIUM: 'Premium',
  MALE: 'Masculino',
  FEMALE: 'Femenino',
  OTHER: 'Otro',
  STARTER: 'Entrada',
  MAIN: 'Principal',
  DESSERT: 'Postre',
  SIDE: 'Acompanamiento',
  SNACK: 'Snack',
  DRINK: 'Bebida',
  SWEET: 'Dulce',
  SALTY: 'Salado',
  ACID: 'Acido',
  BITTERSWEET: 'Agridulce',
  UMAMI: 'Umami',
  SPICY: 'Picante',
  UNKNOWN: 'Sin definir',
  EASY: 'Facil',
  MEDIUM: 'Media',
  HARD: 'Dificil',
  CHEF: 'Profesional',
  SMALL: 'Chico',
  LARGE: 'Grande',
  XL: 'Extra grande',
  PROTEIN_ANIMAL: 'Proteina animal',
  PROTEIN_PLANT: 'Proteina vegetal',
  VEGETABLE: 'Vegetal',
  FRUIT: 'Fruta',
  LEGUME: 'Legumbre',
  GRAIN: 'Cereal',
  BREAD: 'Panificado',
  DAIRY: 'Lacteo',
  FAT: 'Grasa',
  SAUCE: 'Salsa',
  CONDIMENT: 'Condimento',
  SWEETENER: 'Endulzante',
  BEVERAGE: 'Bebida',
  RAW: 'Crudo',
  GRILLED: 'A la plancha',
  FRIED: 'Frito',
  BAKED: 'Horneado',
  ROASTED: 'Asado',
  SAUTEED: 'Salteado',
  BOILED: 'Hervido',
  STEAMED: 'Al vapor',
  SMOKED: 'Ahumado',
  PICKLED: 'Encurtido',
  FERMENTED: 'Fermentado',
  ADDITION: 'Agregado',
  REMOVAL: 'Quita',
  SUBSTITUTION: 'Sustitucion',
  GLUTEN: 'Gluten',
  MILK: 'Leche',
  EGG: 'Huevo',
  PEANUT: 'Mani',
  TREE_NUT: 'Frutos secos',
  SOY: 'Soja',
  SESAME: 'Sesamo',
  FISH: 'Pescado',
  SHELLFISH: 'Mariscos',
  MUSTARD: 'Mostaza',
  CELERY: 'Apio',
  SULFITES: 'Sulfitos',
  VEGETARIAN: 'Vegetariano',
  VEGAN: 'Vegano',
  GLUTEN_FREE: 'Sin gluten',
  DAIRY_FREE: 'Sin lacteos',
  NUT_FREE: 'Sin frutos secos',
  LOW_CARB: 'Bajo en carbohidratos',
  KETO_COMPATIBLE: 'Compatible con keto',
  PALEO_COMPATIBLE: 'Compatible con paleo',
  PESCATARIAN: 'Pescetariano',
  HIGH_PROTEIN: 'Alto en proteina',
  HIGH_FIBER: 'Alto en fibra',
  HIGH_HEALTHY_FATS: 'Alto en grasas saludables',
  LOW_SUGAR: 'Bajo en azucar',
  LOW_SODIUM: 'Bajo en sodio',
  WHOLE_FOOD: 'Comida real',
  MINIMALLY_PROCESSED: 'Minimamente procesado',
  ENERGY_DENSE: 'Alta densidad energetica',
  SATIATING: 'Saciante',
};

const titleCaseFallback = (value: string) =>
  value
    .toLowerCase()
    .split('_')
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(' ');

export const formatEnumLabel = (value: string | null | undefined) => {
  if (!value) return 'No especificado';
  return ENUM_LABELS[value] ?? titleCaseFallback(value);
};
