/**
 * @file prisma.config.ts
 * @module Backend
 * @description Archivo prisma.config alineado a la arquitectura y trazabilidad QART.
 *
 * @tfi
 * section: IEEE 830 13
 * rf: RF-18
 * rnf: RNF-05
 *
 * @business
 * inputs: configuracion de Prisma y resolucion de schema o generator del backend
 * outputs: ajustes de infraestructura para cliente, migraciones o runtime de Prisma
 * rules: mantener coherencia entre schema, generator y entorno de base
 *
 * @technical
 * dependencies: dotenv, prisma/config
 * flow: define la configuracion de Prisma para el workspace; enlaza schema y opciones del cliente; expone la base usada por runtime y tooling.
 *
 * @estimation
 * complexity: Medium
 * fpa: EQ
 * story_points: 3
 * estimated_hours: 2
 *
 * @testing
 * cases: TC-AUDIT-01
 *
 * @notes
 * decisions: la configuracion ORM se centraliza para evitar divergencias entre entorno y codigo
 */
// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { config } from 'dotenv';
config();
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
